# Generated by Django 3.1.5 on 2021-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subgenre',
            new_name='Mood',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sub',
        ),
        migrations.AddField(
            model_name='book',
            name='mood',
            field=models.ManyToManyField(blank=True, related_name='books_ny_mood', to='books.Mood'),
        ),
    ]
